class Bootstrap3ButtonGroup {
  // #region Public Properties

  // This region was generated by a tool.
  // Changes to this region may cause incorrect behavior
  // and will be lost if the code is regenerated.
  public IsVisible: boolean;
  public Tooltip: string;

  // #endregion

  initialize(initial: ComponentOptions, app: Application, el: Element, sitecore: SitecoreSpeak) {
    $(el).find("*[data-toggle]").dropdown();
  }
}

Sitecore.Speak.component(["jquery", "bootstrap"], Bootstrap3ButtonGroup, "Bootstrap3-ButtonGroup");
