class Bootstrap3ButtonDropdown {
  // #region Public Properties

  // This region was generated by a tool.
  // Changes to this region may cause incorrect behavior
  // and will be lost if the code is regenerated.
  public IsEnabled: boolean;
  public IsVisible: boolean;
  public Size: string;
  public Text: string;
  public Tooltip: string;
  public Type: string;

  // #endregion

  initialize(initial: ComponentOptions, app: Application, el: Element, sitecore: SitecoreSpeak) {
    $(el).find("*[data-toggle]").dropdown();
  }
}

Sitecore.Speak.component(["jquery", "bootstrap"], Bootstrap3ButtonDropdown, "Bootstrap3-ButtonDropdown");
