//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sitecore.Shell.Client.Bootstrap3.Layouts.Renderings.Bootstrap3.Components.Bootstrap3Wells
{
  public partial class Bootstrap3WellRenderingModel : Sitecore.Mvc.Presentation.SpeakRenderingModel
  {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string AccessKey { get { return this.GetString("AccessKey"); } }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string Alignment { get { return this.GetString("Alignment"); } }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string Behaviors { get { return this.GetString("Behaviors"); } }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string Emphasis { get { return this.GetString("Emphasis"); } }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public bool EnableScript { get { return this.GetBool("EnableScript"); } }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string Id { get { return this.GetString("Id"); } }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public bool IsVisible { get { return this.GetBool("IsVisible"); } }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string Size { get { return this.GetString("Size"); } }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string Text { get { return this.GetString("Text"); } }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string Tooltip { get { return this.GetString("Tooltip"); } }

  }
}
