class Bootstrap3Abbreviation {
  // #region Public Properties

  // This region was generated by a tool.
  // Changes to this region may cause incorrect behavior
  // and will be lost if the code is regenerated.
  public Initialism: boolean;
  public IsVisible: boolean;
  public Text: string;
  public Tooltip: string;

  // #endregion

  initialize(initial: ComponentOptions, app: Application, el: Element, sitecore: SitecoreSpeak) {
  }
  
}

Sitecore.Speak.component(Bootstrap3Abbreviation, "Bootstrap3-Abbreviation");
