import Speak = require("sitecore/shell/client/Speak/Assets/lib/core/1.2/SitecoreSpeak");

class Bootstrap3Select extends Speak.ControlBase {

  // #region Public Properties

  // This region was generated by a tool.
  // Changes to this region may cause incorrect behavior
  // and will be lost if the code is regenerated.
  public IsEnabled: string;
  public IsVisible: boolean;
  public Items: Array<any>;
  public SelectedItem: string;
  public Text: string;
  public Tooltip: string;
  private initialValue: string;

  // #endregion            

  initialize(initial: ComponentOptions, app: Application, el: Element, sitecore: SitecoreSpeak) {
    var children = $(el).children();
    if (children.length > 0) {
      _.each($(el).children(), (e: Element) => {
        this.Items.push({ DisplayName: $(e).text().trim(), Value: $(e).attr("value").trim() });
      });                           
    }

    this.on("change:SelectedItem", (newValue) => this.setSelectedItem(newValue));

    // this is a hack to prevent Items bindings from overwriting the the SelectedItem binding
    setTimeout(() => {
      if (this.initialValue != null) {
        this.SelectedItem = this.initialValue;
      }
    }, 1);
  }

  initialized() {
  }

  setSelectedItem(newValue: any) {
    if (this.initialValue == null) {
      this.initialValue = newValue;
    }
  }
}

Sitecore.Speak.component(["jquery", "underscore"], Bootstrap3Select, "Bootstrap3-Select");
