class Bootstrap3Select {

  // #region Public Properties

  // This region was generated by a tool.
  // Changes to this region may cause incorrect behavior
  // and will be lost if the code is regenerated.
  public IsEnabled: string;
  public IsVisible: boolean;
  public Items: Array<any>;
  public SelectedItem: string;
  public Text: string;
  public Tooltip: string;

  // #endregion

  initialize(initial: ComponentOptions, app: Application, el: Element, sitecore: SitecoreSpeak) {
    _.each($(el).children(), (e: Element) => {
      this.Items.push({ DisplayName: $(e).text().trim(), Value: $(e).attr("value").trim() });
    });
  }
}

Sitecore.component(["jquery", "underscore"], Bootstrap3Select, "Bootstrap3-Select");
