//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Sitecore.Shell.Client.Bootstrap3.Layouts.Renderings.Bootstrap3.Forms.Bootstrap3Labels
{
  #region Designer generated code

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
  public partial class Bootstrap3LabelRenderingModel : Sitecore.Mvc.Presentation.SpeakRenderingModel
  {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string AccessKey { get { return this.GetString("AccessKey"); } }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string Behaviors { get { return this.GetString("Behaviors"); } }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string For { get { return this.GetString("For"); } }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string Id { get { return this.GetString("Id"); } }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public bool IsControlLabel { get { return this.GetBool("IsControlLabel"); } }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string IsEnabled { get { return this.GetString("IsEnabled"); } }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public bool IsScreenReaderOnly { get { return this.GetBool("IsScreenReaderOnly"); } }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public bool IsVisible { get { return this.GetBool("IsVisible"); } }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string Text { get { return this.GetString("Text"); } }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("SitecoreRocks", "1.0.0.0")]
    public string Tooltip { get { return this.GetString("Tooltip"); } }
  }

  #endregion
}

#pragma warning restore 1591
